### ISSUE TITLE
please explain three-tier a bit more....

### ISSUE THREAD

**Issue by vinceskahan** [vivo-community/vivo-project-template#3]
The Readme gets a little skeletal at best...

What does "Using your change the settings to match your Tomcat installation" mean ?   I'm not able to parse that one mentally.

Down below you say "using Git you can checkout any tagged release, build it with your local changes, and test it out" - where exactly 'are' those local changes in your example ?   A simple hello-world example that sets a banner or css or something trivial and connects everything into a whole example would be appreciated.

**Comment by lawlesst** [comment]
> The Readme gets a little skeletal at best...

There's more information in the linked documents, including this [page in the VIVO wiki](https://wiki.duraspace.org/display/VIVO/Building+VIVO+in+3+tiers)

> What does "Using your change the settings to match your Tomcat installation" mean ?   I'm not able to parse that one mentally.

This was a copy and past error. I've updated this sentence to hopefully clarify. The default paths in the settings file need to be changed to match your environment. 

> Down below you say "using Git you can checkout any tagged release, build it with your local changes, and test it out" - where exactly 'are' those local changes in your example ?   A simple hello-world example that sets a banner or css or something trivial and connects everything into a whole example would be appreciated.

Maybe looking at UNAVCO's project will help. Here is their [theme directory](https://github.com/NCAR/2014-EarthCube-BuildingBlocks-EnablingCollaboration-14402930-vivo-source/tree/develop/unavco-installer/webapp/src/main/webapp/themes).
